---
title: "Analysis of Personal Google Activity"
author: ""
date: ""
output:
  hrbrthemes::ipsum:
    toc: false
    fig_width: 8
    fig_height: 8
---

```{r include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
params <-
  list(
    filepath = "data-raw/Takeout-My Activity-Search-MyActivity.html",
    name_main = "Tony",
    names_main = c("Tony", "Andrew", "Kid"),
    color_main = "firebrick",
    colors_main = c("firebrick", "gold", "royalblue"),
    rgx_ignore_custom = list(Tony = c(""), Andrew = c(""), Kid = c(""))
  )
```


```{r}
library("dplyr")
library("stringr")
library("rvest")
library("lubridate")
library("ggplot2")
```

## Analysis

### Import

```{r}
doc_html <- params$filepath
search_archive <- xml2::read_html(doc_html)
```

### Clean

```{r}
# Extract search time.
date_search <-
  search_archive %>%
  html_nodes(xpath = '//div[@class="mdl-grid"]/div/div') %>%
  str_extract(pattern = "(?<=<br>)(.*)(?<=PM|AM)") %>%
  mdy_hms()

# Extract search text.
text_search <-
  search_archive %>%
  html_nodes(xpath = '//div[@class="mdl-grid"]/div/div') %>%
  str_extract(pattern = '(?<=<a)(.*)(?=</a>)') %>%
  str_extract(pattern = '(?<=\">)(.*)')

# Extract search type.
type_search <-
  search_archive %>% 
  html_nodes(xpath = '//div[@class="mdl-grid"]/div/div') %>% 
  str_extract(pattern = "(?<=mdl-typography--body-1\">)(.*)(?=<a)") %>% 
  str_extract(pattern = "(\\w+)(?=\\s)")

# Use `lubridate::wday()` here instead of `weekdays()` and subsequent coerction to factors.
# Adding a `name` column for coloring purposes later.
data <-
  tibble(
    name = params$name_main,
    timestamp = date_search,
    date = lubridate::as_date(date_search),
    year = lubridate::year(date_search) %>% as.integer(),
    month = lubridate::month(date_search, label = TRUE),
    wday = lubridate::wday(date_search, label = TRUE),
    hour = lubridate::hour(date_search),
    time = lubridate::hour(timestamp) + (lubridate::minute(timestamp) / 60),
    type = type_search,
    text = text_search
  )

```


```{r}
data %>% count(year, sort = TRUE)
data <- data %>% filter(!is.na(year))
```

### Visualize

```{r}
# scales::show_col(params$colors_main)
add_viz_bytime_elements <-
  function(viz,
           geom = c("bar", "hist"),
           colors = NULL,
           lab_subtitle = NULL) {
    geom <- match.arg(geom)
    viz_labs <-
      labs(
        x = NULL,
        y = NULL,
        title = "Count Over Time",
        subtitle = lab_subtitle
      )
    viz_theme <-
      temisc::theme_te_b_facet() +
      theme(panel.grid.major.x = element_blank()) +
      # theme(legend.position = "bottom", legend.title = element_blank())
      theme(legend.position = "none")

    if (geom == "bar") {
      viz <-
        viz +
        geom_bar(aes(y = ..count.., fill = name))
    } else if (geom == "hist") {
      viz <-
        viz +
        geom_histogram(aes(y = ..count.., fill = name), bins = 30)
    }
    viz <-
      viz +
      scale_fill_manual(values = colors) +
      facet_wrap(~ name, ncol = 1, strip.position = "right") +
      viz_labs +
      viz_theme
    viz
  }
```

```{r}
lab_subtitle_all <-
  paste0(
    "From ",
    strftime(data$timestamp[1], "%Y-%m-%d"),
    " to ",
    strftime(rev(data$timestamp)[1], "%Y-%m-%d")
  )

viz_bytime_all <-
  data %>%
  ggplot(aes(x = timestamp)) %>%
  add_viz_bytime_elements(geom = "hist", colors = params$colors_main, lab_subtitle = lab_subtitle_all)

viz_bytime_yyyy <-
  data %>%
  ggplot(aes(x = year)) %>%
  add_viz_bytime_elements(geom = "bar", colors = params$colors_main, lab_subtitle = "By Year")

viz_bytime_mm <-
  data %>%
  ggplot(aes(x = month)) %>%
  add_viz_bytime_elements(geom = "bar", colors = params$colors_main, lab_subtitle = "By Month")

viz_bytime_wday <-
  data %>%
  ggplot(aes(x = wday)) %>%
  add_viz_bytime_elements(geom = "bar", colors = params$colors_main, lab_subtitle = "By Day of Week")

viz_bytime_hh <-
  data %>%
  ggplot(aes(x = hour)) %>%
  add_viz_bytime_elements(geom = "bar", colors = params$colors_main, lab_subtitle = "By Hour of Day")
```

```{r echo = FALSE}
viz_bytime_all
viz_bytime_yyyy 
viz_bytime_mm
viz_bytime_wday
viz_bytime_hh
```

```{r}
viz_bytime_hh_2 <-
  data %>%
  ggplot(aes(x = name, y = time, fill = name)) +
  scale_y_continuous(
    limits = c(1, 24),
    breaks = c(6, 12, 18),
    labels = c("6am", "Noon", "6pm")
  ) +
  scale_fill_manual(values = params$colors_main) +
  geom_violin(size = 0, alpha = 0.7) +
  geom_hline(yintercept = seq(3, 24, by = 3),
             color = "gray",
             size = 0.1) +
  labs(x = NULL, y = NULL, title = "Count Over Time", lab_subtitle = "By Time of Day") +
  temisc::theme_te_b_dx() +
  theme(legend.position = "none", panel.grid = element_blank()) +
  coord_flip()

viz_bytime_hh_wday <-
  data %>%
  filter(name == params$name_main) %>% 
  ggplot(aes(x = hour, group = wday, fill = name)) +
  geom_bar() +
  scale_fill_manual(values = params$colors_main) +
  facet_wrap( ~ wday, scales = "free") +
  labs(x = NULL, y = NULL, title = "Count Over Time", lab_subtitle = "By Hour of Day and Time of Day") +
  temisc::theme_te_b_facet_dx() +
  theme(legend.position = "none", panel.grid = element_blank())

viz_bytime_wday_yyyy <-
  data %>%
  count(name, year, wday) %>%
  ggplot(aes(x = wday, y = n, fill = year)) +
  geom_bar(stat = "identity") +
  facet_wrap(~name, scales = "free") +
  labs(x = NULL, y = NULL, title = "Count Over Time", lab_subtitle = "By Day of Week and Year") +
  # viridis::scale_fill_viridis(discrete = FALSE) +
  temisc::theme_te_b_facet_dx() +
  theme(legend.position = "bottom", panel.grid = element_blank())

```

```{r}
rgx_pattern_search <- '(http|https)\\S+\\s*|(#|@)\\S+\\s*|\\n|\\"|(.*.)\\.com(.*.)\\S+\\s|[^[:alnum:]]'
rgx_replacement_search <- " "
# rgx_unnest_search <- "([^A-Za-z_\\d#@']|'(?![A-Za-z_\\d#@]))"
# rgx_unnest_search <- NULL
# rgx_ignore_custom_search <- c("chrome", "chicago", "jlroo", "google")
# rgx_ignore_custom_search <- NULL

tidy_data_unigrams <-
  function(data = NULL,
           colname_text = "text",
           colname_word = "word",
           rgx_pattern,
           rgx_replacement,
           rgx_unnest,
           rgx_ignore_custom) {
    
    if(is.null(data)) stop("`data` cannot be NULL.", call. = FALSE)
    colname_text_quo <- rlang::sym(colname_text)
    colname_word_quo <- rlang::sym(colname_word)
    
    out <- data
    if (!missing(rgx_pattern) & !missing(rgx_replacement)) {
      out <-
        mutate(out,
               text = str_replace_all(!!colname_text_quo, rgx_pattern, rgx_replacement))
    }
    
    if (missing(rgx_unnest)) {
      out <-
        tidytext::unnest_tokens(out, !!colname_word_quo, !!colname_text_quo)
    } else {
      out <-
        tidytext::unnest_tokens(out, !!colname_word_quo, !!colname_text_quo, rgx_unnest)
    }
    
    if (!missing(rgx_ignore_custom)) {
      out <-
        filter(out, !str_detect(!!colname_word_quo, rgx_ignore_custom))
    }
    
    out <- filter(out, str_detect(!!colname_word_quo, "[a-z]"))
    out
  }

tidy_data_bigrams <-
  function(data = NULL,
           colname_text = "text",
           colname_words = "bigram", 
           colname_word1 = "first",
           colname_word2 = "second",
           rgx_pattern,
           rgx_replacement,
           rgx_ignore_custom) {

    if(is.null(data)) stop("`data` cannot be NULL.", call. = FALSE)
    colname_text_quo <- rlang::sym(colname_text)
    colname_words_quo <- rlang::sym(colname_words)
    colname_word1_quo <- rlang::sym(colname_word1)
    colname_word2_quo <- rlang::sym(colname_word2)

    out <- data
    if (!missing(rgx_pattern) & !missing(rgx_replacement)) {
      out <-
        dplyr::mutate(out,
               text = stringr::str_replace_all(!!colname_text_quo, rgx_pattern, rgx_replacement))
    }
    out <- tidytext::unnest_tokens(out, !!colname_words_quo, !!colname_text_quo, token = "ngrams", n = 2)
    out <- tidyr::separate(out, !!colname_words_quo, 
                           into = c(colname_word1, colname_word2), sep = " ", remove = FALSE)
    # browser()
    # NOTE: Get an error for this?!?
    # out <- dplyr::anti_join(out, tidytext::stop_words, by = c(colname_word1 = "word"))
    out <- dplyr::anti_join(out, tidytext::stop_words, by = c("first" = "word"))
    # out <- dplyr::anti_join(out, tidytext::stop_words, by = c(colname_word2 = "word"))
    out <- dplyr::anti_join(out, tidytext::stop_words, by = c("second" = "word"))
    if (!missing(rgx_ignore_custom)) {
      out <-
        dplyr::filter(out, !stringr::str_detect(!!colname_word1_quo, rgx_ignore_custom))
      out <-
        dplyr::filter(out, !stringr::str_detect(!!colname_word2_quo, rgx_ignore_custom))
    }

    out <- dplyr::filter(out, stringr::str_detect(!!colname_word1_quo, "[a-z]"))
    out <- dplyr::filter(out, stringr::str_detect(!!colname_word2_quo, "[a-z]"))
    out
  }
```

```{r}
data_tidy_unigrams <-
  data %>%
  tidy_data_unigrams(
    rgx_pattern = rgx_pattern_search, 
    rgx_replacement = rgx_replacement_search
  )

data_tidy_unigrams %>% select(word, name) %>% count(word, sort = TRUE)

data_tidy_bigrams <-
  data %>%
  tidy_data_bigrams(
    rgx_pattern = rgx_pattern_search, 
    rgx_replacement = rgx_replacement_search
  )
data_tidy_bigrams %>% select(bigram, name) %>% count(bigram, sort = TRUE)
```

```{r}
get_ngrams_freqs_byx <-
  function(data = NULL, 
           colname_x = "name", 
           colname_cnt = "word") {
  
  if(is.null(data)) stop("`data` cannot be NULL.", call. = FALSE)
  colname_x_quo <- rlang::sym(colname_x)
  colname_cnt_quo <- rlang::sym(colname_cnt)
  
  ngrams_cnt_1 <- dplyr::count(data, !!colname_x_quo)
  ngrams_cnt_2 <- dplyr::count(data, !!colname_x_quo, !!colname_cnt_quo)

  ngrams_joined <- dplyr::left_join(ngrams_cnt_1, dplyr::rename(ngrams_cnt_2, total = n), by = "name")
  out <- dplyr::mutate(ngrams_joined, freq = n / total)
  out <- dplyr::arrange(out, dplyr::desc(freq))
  out
}

```

```{r}
unigrams_byname_freqs <- get_ngrams_freqs_byx(data_tidy_unigrams, colname_x = "name", colname_cnt = "word")
bigrams_byname_freqs <- get_ngrams_freqs_byx(data_tidy_bigrams, colname_x = "name", colname_cnt = "bigram")
```

```{r}
visualize_ngrams_byname_freqs_wordcloud <-
  function(data, name_filter, color, max_words = 50) {
    data_proc <-
      data %>%
      filter(name == name_filter)
    out <-
      wordcloud::wordcloud(
        word = data_proc$word,
        freq = data_proc$n,
        max.words = max_words,
        random.order = FALSE,
        colors = color
      )
    out
  }
```

```{r, echo = FALSE}
num_par_row <- ceiling(length(params$names_main) / 3)
num_par_col <- min(length(params$names_main), 3)
```

```{r, echo = FALSE}
par(mfrow = c(num_par_row, num_par_col))
```

```{r}
purrr::map2(
  # params_proc$names_main,
  params$name_main,
  # params_proc$colors_main,
  params$color_main,
  ~visualize_ngrams_byname_freqs_wordcloud(
    data = unigrams_byname_freqs,
    name_filter = .x,
    color = .y
  )
)

```

```{r, echo = FALSE}
par(mfrow = c(1, 1))
```

```{r, echo = FALSE}
par(mfrow = c(num_par_row, num_par_col))
```

```{r, results = "hide"}
purrr::map2(
  # params_proc$names_main,
  params$name_main,
  # params_proc$colors_main,
  params$color_main,
  ~visualize_ngrams_byname_freqs_wordcloud(
    data = bigrams_byname_freqs %>% rename(word = bigram),
    name_filter = .x,
    color = .y
  )
)
```

```{r, echo = FALSE}
num_par_row <- ceiling(length(params_proc$names_main) / 3)
num_par_col <- min(length(params_proc$names_main), 3)
par(mfrow = c(1, 1))
```

```{r, results = "hide"}
purrr::map2(
  # params_proc$names_main,
  params$name_main,
  # params_proc$colors_main,
  params$color_main,
  ~visualize_ngrams_byname_freqs_wordcloud(
    data = bigrams_byname_freqs,
    name_filter = .x,
    color = .y
  )
)
```

```{r}
num_top_bigram_freq <- floor(12 / length(params$names_main))
bigrams_byname_freqs_viz <-
  bigrams_byname_freqs %>%
  group_by(name) %>%
  mutate(rank = row_number(desc(freq))) %>%
  filter(rank <= num_top_bigram_freq) %>%
  ungroup() %>%
  arrange(name) %>%
  mutate(bigram = str_replace_all(bigram, " ", "\n")) %>%
  mutate(bigram = forcats::fct_reorder(factor(bigram), freq))

viz_bigrams_byname_freqs <-
  bigrams_byname_freqs_viz %>%
  ggplot(aes(x = name, y = bigram, color = name, size = freq)) +
  geom_point() +
  scale_y_discrete(position = "right") +
  scale_color_manual(values = params_proc$colors_main) +
  scale_size_area(max_size = 25) +
  labs(x = NULL, y = NULL) +
  labs(title = "Most Frequently Used Pairs of Words", subtitle = "By Name") +
  temisc::theme_te_b() +
  theme(legend.position = "none") +
  coord_flip()
```


